### ISSUE TITLE
Individual Explorer: Guide hangs after last prompt.

### ISSUE THREAD

**Issue by AARON-CLARK** [Biogen-Inc/tidyCDISC#201] opened 2023-03-08 18:28 UTC
On the Individual Explorer:

I was testing the guide button [ ? ] under the Visits tab.

The last popup window does not have a "Done" button like the other guides, so when you click "Next", it just leaves you with a highlighted box. You can then click on the page to make it go away.

_Originally posted by @tdwils in https://github.com/Biogen-Inc/tidyCDISC/issues/172#issuecomment-1458898333_

**Comment by AARON-CLARK** [comment] 2023-03-09 13:06
Hi @tdwils, I can't seem to reproduce this issue. Is there some other action you performed in the app to trigger this event? This happened before updating all your pkgs, right? Perhaps we should create a separate branch that everyone could use with all pkgs updated. I'll work on that now. 

According to [this](https://github.com/Biogen-Inc/tidyCDISC/blob/94db35af20705a1ec940c8d29545fda2213fc0e5/R/mod_indvExpPatVisits.R#L38-L52) code chunk, there are three different guides the app will render depending on what datasets are loaded. 

(1) With no BDS data loaded:
![image](https://user-images.githubusercontent.com/17878953/224031136-071d4518-e856-4645-b9c8-f687b2405241.png)

(2) With a BDS data loaded, but no ADLB (2) with BDS loaded, including an ADLB. I tested both of these events, and they both end on the same step (with a "Done" button).
![image](https://user-images.githubusercontent.com/17878953/224029921-e33ed490-285c-4bad-9e15-6e4aadba80ab.png)

Can you please test again? If it doesn't happen again, perhaps we can mark this one as closed?

**Comment by tdwils** [comment] 2023-03-09 13:35
@AARON-CLARK  Yes, this was before updating all the packages. I can't reproduce it now, but it was definitely happening. I will close this issue and then watch out for it.

**Closed by tdwils** 2023-03-09 13:35 UTC
